travis:
  secure:
    BINSTAR_TOKEN: nm2a2Bk/un7WcxA2G/em1NoHbZBAgFl1FRvwef34etyfj5jfWCSiy7K033KtR8c8mugn9jtd08TD8R9HDlPBaMG9s2fsYk85GaUThju4GB6ZYczUimeiL7MPah0j1dgYdQT6iVa5aQrwJRBDpGMsgv/58i5R2HSMfZzshOQPD4YvsAFoydi2HCMGe69gLvD9svMHCjnVWACYNK21wbShIM3GDp8ImYe3yPkpFhZr02kN/VyF/qaUMOiLuzJzDo6rN1cdbMobJ9OR3sHMgH+0i1Ug2SiYFteWRhJKlODa15ULdSCVHw2A/K5AMdsKIGTJMrqpC47+FF1jxqZRc4jVWgHst6bcZc/v6O8Hi++/7bKYchYT+bNN9t9bSoYfr1M6ann/xrlKXHrg8TEN2fbIVdXHcZ3NvXaBW65ajTLF5R8QSXsjXgBJYgB+svvdqJjZB4xaW96KLgGJmZk0W/JvTfdJ19NJixYLwcMOCwM/7CBmKxBm5oKTyzzlLhjf1jE3CQfflu0gUe73Q40oZEuO60E/9PB4iSESYvelEawUyYuUoA2b5si8s9L6+YVijd04lTpDSL9v0j4I5jXTD6/pZbfXp5JPjewtbG8brxBSJuFzPlzK5NtxsTVoiMRVr0zDNVa+UV+npsXwRkjzQqYFV+QTdzW1mrzuRCndolbrf58=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
